
{{ if hasKey .Values.env }}
  {{ fail "The Value env has been renamed and moved to pleach.configEnv. Refer to https://www.pleach.ai/docs/local/helm_chart#migrate for more information" }}
{{ end }}